### ISSUE TITLE
Enable Education Locked Stacks material to be mediated

### ISSUE THREAD

**Issue by jkeck** [sul-dlss/sul-requests#1075]
Education is/will be closed for renovations.

This will be similar to ART Locked Stacks in that there will be a location w/i EDUCATION that will need to be requestable to SPEC-COLL.

### TODO
- [x] Create workgroup for mediators: sul:requests-education
- [x] Create email list for mediators: sul-requests-education
- [x] Determine any eligibility overlay wording necessary (See [ART's](https://github.com/sul-dlss/sul-requests/blob/master/app/views/mediated_pages/_ART_eligibility_confirmation.html.erb) for an example): no significant change needed.  See below
- [x] Update requests configuration to add EDUCATION as a mediatable origin.
- [x] Update SearchWorks to enable request links for these materials

This can be deployed as soon as it's ready.

**Comment by saseestone** [comment]
Example item: https://searchworks.stanford.edu/view/8336067
Location to include: LOCKED-STK

**Comment by saseestone** [comment]
No significant changes to the overlay for Education.  We should update references to the library to read "Education Library" but that's the only change.

header: Education Locked Stacks request
intro paragraph: <strong>The Education Library is currently closed.</strong> Restricted items are made available for use in the Special Collections Reading Room of Green Library.

The rest of the overlay should read exactly the same as the Art one.

**Comment by camillevilla** [comment]
@saseestone Ok! This has been deployed to dev for testing tomorrow.

**Comment by saseestone** [comment]
Links in SW look good and form looks great.  

The confirmation mailer is a little off. It directs users with questions to contact Special Collections, but we really should be directing to Education staff. Looking at the Art Locked Stacks set up, it appears that we didn't change that for Art either.  (eeek.)

But there's a place to put in location specific contact information in the sul-requests/spec/mailers/confirmation_mailer_spec.rb.  We've got contact info for branner.  We should add Education and Art if possible.

Education:
(650) 723-2121
cubberley@stanford.edu

Art:
(650) 723-3408
artlibrary@stanford.edu

It would be best to have the reply to for the mailer also be from Education/Art.

**Comment by camillevilla** [comment]
Deployed 4/2
