### ISSUE TITLE
CSS tweaks

### ISSUE THREAD

**Issue by jvine** [sul-dlss/sul-requests#297]
Within the context of requests - these changes should not affect SW except where noted.

* [x] h1 {padding-bottom: 0;}
* [x] .form-group h2, .form-group .success-page .requested-by, .success-page .form-group .requested-by, .searchworks-item {line-height: 1.6em; margin-bottom: .5em}
* [x] .help-block {color: #737373; margin-bottom: 0;}
* [x] .btn-md { font-size: 1.1em;}
* [x] .btn-sub-text { font-size: 0.85em;}
* [x] .item-selector {max-height: 200px;}
* [x] .form-group .required:after {content: "Required"; margin-left: 5px;}
* [x] .or-divider {color: #737373; }
* [x] .zero-items-message {padding-top: 7px; color: #737373;}
* [x] .sort-headings .sort i {float: none !important; margin-left: 15px;} /* remove float: right */
* [x] p.form-control-static {padding-bottom: 0; min-height: 0}

* [x] couldn't add a style for this directly - please add an additional 15px vertical whitespace between the last form content and the login/send group. (The user name is part of the login/send group.)

And this is for the popup itself, so in SW:
* [x] .requests-modal .modal-content .modal-body .form-group {box-shadow: 0px -4px 8px 0px rgba(95,87,79,0.25); margin: 0px -15px; padding: 5px 15px;}
* [x] .requests-modal .modal-content .modal-body {height: 700px;}

**Comment by jgreben** [comment]
Do you want .btn-md to always be 1.1em? It is currently set to `1.1 * 14px`.

.btn-md {
  font-size: 1.1 * $font-size-base;
}

**Comment by jvine** [comment]
Ah okay - I was seeing it as the computed pixel size, and not enough contrast between the two font sizes. It's fine, just adjust the btn-sub-text and it will be ok.

**Comment by jgreben** [comment]
I'm not exactly sure where you mean by this. Do you have a screenshot per chance?
`couldn't add a style for this directly - please add an additional 15px vertical whitespace between the last form content and the login/send group. (The user name is part of the login/send group.)`

**Comment by jvine** [comment]
In other words, don't add space between the name and the button, when the name is present - add it above the name.

Before
![screen shot 2015-08-14 at 4 01 39 pm](https://cloud.githubusercontent.com/assets/6945691/9285739/ec759bc2-429d-11e5-94a8-92387083e5f5.png)

After
![screen shot 2015-08-14 at 2 57 36 pm](https://cloud.githubusercontent.com/assets/6945691/9285742/f42d38e8-429d-11e5-91ee-c4e3bf1462e8.png)


Before
![screen shot 2015-08-14 at 4 03 41 pm](https://cloud.githubusercontent.com/assets/6945691/9285760/29b49894-429e-11e5-9f74-6a30b3800ac3.png)

After
![screen shot 2015-08-14 at 4 04 09 pm](https://cloud.githubusercontent.com/assets/6945691/9285761/2fcf8e1e-429e-11e5-86e8-5da7f405b29c.png)

**Comment by jgreben** [comment]
Can this be closed?  Does the rest of this need to be am issue in SW?

And this is for the popup itself, so in SW:

 .requests-modal .modal-content .modal-body .form-group {box-shadow: 0px -4px 8px 0px rgba(95,87,79,0.25); margin: 0px -15px; padding: 5px 15px;}
 .requests-modal .modal-content .modal-body {height: 700px;}

**Comment by jkeck** [comment]
I will close it when I make the appropriate SW changes.
